### ISSUE TITLE
about calculation and visualization on CARLA dataset

### ISSUE THREAD

**Issue by JunyaoHu** [plai-group/flexible-video-diffusion-modeling#7]
1. about calculation of WD and OP on CARLA, how to calculate them? can you share your code?
2. I have got coordinates of 1000 frames, then how to draw a car trajectory (blue points) on total carla map (black transportation network) like which shows in your paper?

![image](https://github.com/plai-group/flexible-video-diffusion-modeling/assets/67564714/3c3ffc3c-0469-4f34-ba74-c38367337220)

**Comment by JunyaoHu** [comment]
I try to draw 100 1000-frames trajectory (100 videos in test dataset), the scatterplot will be like this.

```
# python ./metrics_carla/draw_car_trajectory.py

import torch
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams

config = {
    "mathtext.fontset":'stix',
    "font.serif": 'Times New Roman', 
}
rcParams.update(config)

custom_params = {
    'font.family': 'serif',
    'axes.edgecolor': 'black',
    'grid.color': '#e5e5e5',
    'xtick.bottom': True,
    'ytick.left': True,
    'xtick.direction': 'in',
    'ytick.direction': 'in',
}

sns.set_context("paper")
sns.set_style("whitegrid", rc=custom_params)

file_path = "./result/coords_origin.pt"

coordinates = torch.load(file_path)

# [-10 ~ 400]  [-10 ~ 350]
print(coordinates.shape, torch.min(coordinates[:,:,0]), torch.max(coordinates[:,:,0]),torch.min(coordinates[:,:,1]),torch.max(coordinates[:,:,1]))

for trajectory in coordinates:
    # print(trajectory.shape)
    sns.scatterplot(
        x=trajectory[:,0], y=trajectory[:,1]
    )
```

![image](https://github.com/plai-group/flexible-video-diffusion-modeling/assets/67564714/2954b686-c0ab-4696-bdb8-88c55c29ce7c)

**Comment by wenyufeng936** [comment]
Hello, have you reproduced the results of this paper??

**Comment by JunyaoHu** [comment]
> Hello, have you reproduced the results of this paper??

No, I don't know the calculation formula. And it takes too long to generate videos, and it's difficult to implement.

**Comment by wenyufeng936** [comment]
Can't we reproduce the results of the paper based on the provided code?

**Comment by JunyaoHu** [comment]
> Can't we reproduce the results of the paper based on the provided code?

If you have enough GPUs and time to inference, it should be OK... I tried to generate it, but it was slow.

**Comment by wsgharvey** [comment]
Hi, I'm sorry for the slow response. If you're still interested, please see some of the jupyter notebooks in https://github.com/wsgharvey/video-diffusion/tree/main/notebooks for the plotting code. In particular, `notebooks/carla-make-scatter-with-overlay.ipynb` contains code for the plot you mentioned. The notebook is a bit messy but hopefully contains some code snippets you can use. A key thing to note is that the black lines are drawn using ground-truth coordinates form the dataset in coords.py.

For the OP and WD metrics, I just wrote up this snippet which will work if you replace `gt_coordinates` and `sampled_coordinates` with the right values:
```
import numpy as np
import scipy

gt_coordinates = 2 * np.random.randn(100, 1000, 2)  # compute by running regressor on dataset videos
sampled_coordinates = 2 * np.random.randn(100, 1000, 2)  # compute by running regressor on sampled video

# coordinates are in meters, recoded at 10 fps
def get_speeds(coordinates):
    # frame rate is 10fps so this gets speeds in meters / second
    speeds = np.linalg.norm(coordinates[:, 10:, :] - coordinates[:, :-10, :], axis=2)
    return np.reshape(speeds, -1)

gt_speeds = get_speeds(gt_coordinates)
sampled_speeds = get_speeds(sampled_coordinates)
sampled_outliers = sampled_speeds > 10
sampled_non_outliers = [s for s, o in zip(sampled_speeds, sampled_outliers) if not o]


OP = sampled_outliers.mean()
WD = scipy.stats.wasserstein_distance(gt_speeds, sampled_non_outliers)
```
