### ISSUE TITLE
Total training time

### ISSUE THREAD

**Issue by tarashakhurana** [plai-group/flexible-video-diffusion-modeling#8]
Hi, for the experiments reported in your paper, how much total training time does your model take?

**Comment by wenyufeng936** [comment]
Hello, how much time did you spend training the model when reproducing this paper?

**Comment by wsgharvey** [comment]
Hi, sorry for the slow response. This is in Appendix A of https://arxiv.org/pdf/2205.11495 (we report GPU-hours and number of GPUs). Our largest scale experiment on CARLA Town01 used 380 GPU-hours parallelised on 4 GPUs, so 95 hours.
